name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t saireddyml/contentinsights-rag:latest .

    - name: Check the existing Docker images
      run: docker images

    - name: Get the Image ID for contentinsights-rag:latest
      id: image_id # stores output in a variable
      run: echo "::set-output name=image_id::$(docker images -q saireddyml/contentinsights-rag:latest)"

    - name: Tag the image with contentinsights-rag:latest
      run: docker tag ${{ steps.image_id.outputs.image_id }} saireddyml/contentinsights-rag:latest

    - name: Push to Docker Hub
      run: docker push saireddyml/contentinsights-rag:latest
