name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker HUB
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build --build-arg OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} -t contentinsights-rag .
    - name: Check the Existing docker images
      run: docker images
    - name: Latest tag name 
      run: docker images -q saireddyml/chatbot20.0:latest
    - name: Fetch tag of required images
      env: 
        tag: docker images -q saireddyml/chatbot20.0:latest

    - name: Assigning the tag name to image
      run:  docker tag ${{tag}} saireddyml/contentinsights-rag:latest
    - name: Push to Docker HUB
      run: docker push saireddyml/contentinsights-rag:latest
      
      
